from Crypto.Util.number import *

a = 'OongaOongaBoongaBoongaOongaBoongaBoongaBoongaOongaOongaBoongaBoongaOongaBoongaOongaBoongaOongaOongaBoongaBoongaOongaBoongaOongaOongaOongaOongaBoongaBoongaOongaOongaBoongaOongaOongaOongaBoongaBoongaOongaOongaOongaBoongaOongaOongaBoongaBoongaOongaBoongaOongaOongaOongaOongaBoongaBoongaOongaBoongaOongaOongaOongaOongaBoongaBoongaOongaBoongaBoongaOongaOongaOongaBoongaBoongaOongaBoongaBoongaOongaOongaOongaBoongaBoongaBoongaOongaOongaBoongaOongaOongaBoongaBoongaOongaOongaOongaBoongaOongaOongaBoongaBoongaBoongaOongaOongaBoongaOongaOongaBoongaBoongaOongaOongaOongaBoongaOongaOongaBoongaBoongaOongaBoongaBoongaBoongaOongaOongaBoongaBoongaOongaOongaBoongaBoongaOongaOongaBoongaBoongaBoongaOongaOongaBoongaOongaOongaBoongaBoongaOongaBoongaOongaOongaOongaOongaBoongaBoongaBoongaOongaOongaBoongaOongaOongaBoongaBoongaOongaBoongaOongaBoongaOongaOongaBoongaBoongaOongaOongaBoongaOongaOongaOongaBoongaBoongaOongaBoongaOongaBoongaOongaOongaBoongaBoongaOongaOongaOongaOongaOongaOongaBoongaBoongaBoongaOongaOongaBoongaOongaOongaBoongaBoongaOongaOongaOongaOongaOongaOongaBoongaBoongaOongaBoongaBoongaOongaOongaOongaBoongaBoongaOongaBoongaOongaBoongaOongaOongaBoongaBoongaOongaBoongaBoongaOongaOongaOongaBoongaBoongaOongaBoongaOongaOongaOongaOongaBoongaBoongaOongaBoongaBoongaOongaOongaOongaBoongaBoongaOongaOongaBoongaBoongaOongaOongaBoongaBoongaOongaOongaBoongaBoongaOongaOongaBoongaBoongaOongaBoongaBoongaBoongaOongaOongaBoongaBoongaOongaBoongaBoongaBoongaOongaOongaBoongaBoongaOongaBoongaBoongaBoongaOongaOongaBoongaBoongaOongaOongaOongaOongaOongaOongaBoongaBoongaOongaBoongaBoongaOongaOongaOongaBoongaBoongaOongaOongaOongaBoongaOongaOongaBoongaBoongaOongaBoongaBoongaBoongaOongaOongaBoongaBoongaOongaOongaOongaBoongaOongaOongaBoongaBoongaBoongaOongaOongaBoongaOongaOongaBoongaBoongaOongaOongaOongaBoongaOongaOongaBoongaBoongaBoongaOongaOongaOongaOongaOongaBoongaBoongaOongaOongaBoongaBoonga'
b = 'OongaOongaBoongaBoongaOongaBoongaOongaOongaOongaOongaBoongaBoongaBoongaOongaOongaOongaOongaOongaBoongaBoongaOongaOongaBoongaOongaOongaOongaBoongaBoongaOongaBoongaBoongaOongaOongaOongaBoongaBoongaOongaBoongaBoongaBoongaOongaOongaBoongaBoongaOongaBoongaBoongaOongaOongaOongaBoongaBoongaOongaOongaOongaBoongaOongaOongaBoongaBoongaOongaBoongaBoongaOongaOongaOongaBoongaBoongaOongaOongaBoongaOongaOongaOongaBoongaBoongaBoongaOongaOongaOongaOongaOongaBoongaBoongaOongaBoongaOongaOongaOongaOongaBoongaBoongaOongaBoongaOongaOongaOongaOongaBoongaBoongaOongaBoongaBoongaOongaOongaOongaBoongaBoongaOongaOongaBoongaOongaOongaOongaBoongaBoongaOongaOongaBoongaOongaOongaOongaBoongaBoongaOongaOongaOongaOongaOongaOongaBoongaBoongaOongaBoongaOongaBoongaOongaOongaBoongaBoongaOongaOongaOongaOongaOongaOongaBoongaBoongaOongaBoongaBoongaOongaOongaOongaBoongaBoongaOongaBoongaOongaBoongaOongaOongaBoongaBoongaBoongaOongaOongaBoongaOongaOongaBoongaBoongaOongaOongaBoongaOongaOongaOongaBoongaBoongaOongaBoongaOongaBoongaOongaOongaBoongaBoongaOongaBoongaOongaOongaOongaOongaBoongaBoongaOongaOongaOongaOongaOongaOongaBoongaBoongaOongaOongaBoongaBoongaOongaOongaBoongaBoongaBoongaOongaOongaOongaOongaOongaBoongaBoongaOongaOongaOongaBoongaOongaOongaBoongaBoongaOongaBoongaBoongaBoongaOongaOongaBoongaBoongaBoongaOongaOongaOongaOongaOongaBoongaBoongaOongaOongaBoongaOongaOongaOongaBoongaBoongaOongaBoongaBoongaOongaOongaOongaBoongaBoongaOongaBoongaOongaOongaOongaOongaBoongaBoongaOongaBoongaBoongaOongaOongaOongaBoongaBoongaOongaBoongaOongaBoongaOongaOongaBoongaBoongaBoongaOongaOongaOongaOongaOongaBoongaBoongaBoongaOongaOongaOongaOongaOongaBoongaBoongaOongaBoongaBoongaBoongaOongaOongaBoongaBoongaOongaBoongaBoongaOongaOongaOongaBoongaBoongaOongaOongaOongaBoongaOongaOongaBoongaBoongaOongaOongaBoongaBoonga'

a = a.replace("Oonga", "0")
a = a.replace("Boonga", "1")
b = b.replace("Oonga", "0")
b = b.replace("Boonga", "1")

res = ""

for i in range(len(a)):
    res += a[i]
    if i % 8 == 7: res += ' '

for i in range(len(b)):
    res += b[i]
    if i % 8 == 7: res += ' '

res = res.split()
res1 = ""

for _ in res:
    res1 += chr(int(_, 2))

print(long_to_bytes(int(res1, 10)).decode())

# Flag : ccsCTF{4r3_y0u_enj0yin9_th3_chall5}